### PR TITLE
login popup submit button disabled attribute added

### LINKED ISSUE #40: [Login popup] Login button is clickable without entering any data in Email and Password field
**Environment:** Windows10 21H2, Chrome 112.0.5615.138
**Reproducible:** always

**Preconditions**
The user is on website

**Steps to reproduce**

1. Click Login button in the upper right corner of the header
2. Hover the mouse that the cursor fall on Login button and hover back outside
3. Click on Login button

**Expected result**
The Login button should be unclickable, nothing should happen

### PR DESCRIPTION
**Pull request by tufned**
The Login button is unclickable if inputs are empty

### CODE REVIEW

**Review by grbvtsk — APPROVED** [review]

**Review by HalynaProlubshchykova — APPROVED** [review]

File: src/containers/guest-home-page/login-form/LoginForm.jsx [hunk 1]
```diff
@@ -70,7 +70,16 @@ const LoginForm = ({
         {t('login.forgotPassword')}
       </Typography>
 
-      <AppButton loading={authLoading} sx={styles.loginButton} type='submit'>
+      <AppButton
+        disabled={
+          !Object.values(data).every((value) => value) ||
+          !(data.password.length >= 8 && data.password.length <= 25) ||
+          !Object.values(errors).every((value) => !value)
```
Comment (vlad-khrychov) [inline src/containers/guest-home-page/login-form/LoginForm.jsx]: Maybe we should use validation rules from `src/utils/validations/common.ts`?

**Review by vlad-khrychov — CHANGES_REQUESTED** [review]

File: src/containers/guest-home-page/login-form/LoginForm.jsx (hunk 1 above)
Comment (tufned) [reply src/containers/guest-home-page/login-form/LoginForm.jsx]: Yes, right!
Changes are made,
Thank you for the comment

**Review by vlad-khrychov — APPROVED** [review]
